/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IAuctionContract {
    function owner() external view returns (string memory);
}

interface IUranus is IAuctionContract {
    function setAsset(address _asset) external returns (address);
}
